package com.edu.less08.controller;

public enum CommandName {
    NO_SUCH_COMMAND,
    GO_TO_MAIN_PAGE,
    GO_TO_AUTH_PAGE,
    GO_TO_REGISTRATION_PAGE,
    DO_AUTH,
    DO_REGISTRATION,
    DO_LOG_OUT,
    ADD_COMMENT,
    EDIT_COMMENT,
    REMOVE_COMMENT,
    ADD_COMPLAINT,
    PROCESS_COMPLAINT,
    ADD_NEWS,
    APPROVE_NEWS,
    REMOVE_NEWS,
    EDIT_NEWS,
    SET_MODERATOR
}
